version: '3'

services:
  sources:
    image: postgres:latest
    container_name: sources
    restart: always
    environment:
      - POSTGRES_DB=${SRC_POSTGRES_DB}
      - POSTGRES_USEfR=${SRC_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SRC_POSTGRES_PASSWORD}
    ports:
      - ${SRC_POSTGRES_PORT}:5432
    networks:
      - airflow-networks
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - source-volume:/var/lib/postgresql/data


networks:
  airflow-networks:
    external: true
    name: airflow-networks

volumes:
  source-volume:
    driver: local
    name: source-volume