services:
  metabase-db:
    image: postgres:15
    container_name: metabase-db
    restart: always
    hostname: metabase-db
    ports:
      - "5435:5432"  # External 5435 -> Internal 5432
    environment:
      POSTGRES_DB: metabase_db
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: metabase_pass
    networks:
      - airflow-networks
    volumes:
      - metabase_db_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d  # Mount for init scripts
      - ./data:/var/lib/postgresql/backup 

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    ports:
      - "8083:3000"
    env_file:
      - .env
    networks:
      - airflow-networks
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - metabase-db
    healthcheck:
      test: curl --fail -I http://localhost:8083/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  metabase_db_data:
  metabase_data:

networks:
  airflow-networks:
    external: true
